// lit/runtime/src/main/codestarts/quarkus/quakus-hilla-maven-codestart/base/src/main/frontend/views/about/about-view.ts
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { View } from '../../views/view.js';

@customElement('about-view')
export class AboutView extends View {
  render() {
    return html`<div>
      <img style="width: 200px;" src="images/empty-plant.png" />
      <h2 class="mt-xl mb-m">This place intentionally left empty</h2>
      <p>It’s a place where you can grow your own UI 🤗</p>
    </div>`;
  }

  connectedCallback() {
    super.connectedCallback();
    this.classList.add(
      'flex',
      'flex-col',
      'h-full',
      'items-center',
      'justify-center',
      'p-l',
      'text-center',
      'box-border',
    );
  }
}

// integration-tests/hybrid-smoke-tests/src/main/frontend/views/AboutView.tsx
import { ViewConfig } from "@vaadin/hilla-file-router/types.js";

export const config: ViewConfig = {
    title: "About",
    route: "about"
};

export default function AboutView() {
    return (
        <div className="flex flex-col h-full items-center justify-center p-l text-center box-border">
            <img style={{ width: '200px' }} src="images/empty-plant.png"/>
            <h2 className="mt-xl mb-m">This place intentionally left empty</h2>
            <p>It’s a place where you can grow your own UI 🤗</p>
        </div>
    )
}
